"""
Friendly Django Settings for ConnectlyProject

Generated by Django 5.1.5 using 'django-admin startproject'.
For more details, visit: https://docs.djangoproject.com/en/5.1/topics/settings/

Feel free to tweak these settings to suit your project needs.
"""

from pathlib import Path

# Define the base directory of your project
BASE_DIR = Path(__file__).resolve().parent.parent

# --- General Project Settings ---

# Make sure to keep your secret key private in production!
SECRET_KEY = 'django-insecure-nm!fct80jb#@z0+_8htf09#(3)e9em(vj641*o6p$(mnityzyo'

# Enable debug mode for development only. Switch to False for production!
DEBUG = True

# Specify the hosts your project will serve
ALLOWED_HOSTS = []

# --- Installed Apps ---
# These are the built-in and third-party apps your project is using.
INSTALLED_APPS = [
    'django.contrib.admin',         # Admin interface
    'django.contrib.auth',          # Authentication system
    'django.contrib.contenttypes',  # Framework for content types
    'django.contrib.sessions',      # Session framework
    'django.contrib.messages',      # Messaging framework
    'django.contrib.staticfiles',   # Static file handling
    'django_extensions',            # Handy Django extensions
    'rest_framework',               # Django REST Framework
    'rest_framework.authtoken',     # Authentication tokens for APIs
    'posts',                        # Your custom app for blog posts
]

# --- Middleware ---
# Middleware layers for processing HTTP requests and responses.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL configuration for the project
ROOT_URLCONF = 'ConnectlyProject.urls'

# --- Templates ---
# Manage templates and context processors for rendering views.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add template directories here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application for running the project
WSGI_APPLICATION = 'ConnectlyProject.wsgi.application'

# --- Database ---
# Specify your database settings here
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite database
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Password Validation ---
# Strengthen security by applying these password validators.
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Password Hashers ---
# Define how passwords should be stored securely.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# Configure language and timezone settings for the project.
LANGUAGE_CODE = 'en-us'  # Default language
TIME_ZONE = 'UTC'        # Default timezone
USE_TZ = True            # Enable timezone support


# Set up handling for CSS, JavaScript, and image assets.
STATIC_URL = 'static/'

# --- Default Primary Key Field Type ---
# This setting defines the default type for primary keys in your models.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Security Settings ---
# Make sure to update these for production environments.
SECURE_SSL_REDIRECT = True
"""
# Uncomment the lines below for stronger security in production:
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
"""
